# Generated by Django 3.1.3 on 2020-12-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('package_size', models.DecimalField(blank=True, decimal_places=1, default='0', max_digits=3, null=True)),
                ('state', models.CharField(choices=[('Actual', 'Actual'), ('Planned', 'Planned'), ('Spoilage', 'Spoilage'), ('Defective', 'Defective')], default='Planned', max_length=10)),
                ('received_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('received_by', models.CharField(blank=True, max_length=50, null=True)),
                ('num_orders', models.IntegerField(blank=True, default='0', null=True)),
                ('sold_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('sold_by', models.CharField(blank=True, max_length=50, null=True)),
                ('sold_to', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Fulfilled', 'Fulfilled'), ('Canceled', 'Canceled')], default='Placed', max_length=10)),
                ('is_express_shipping', models.BooleanField(blank=True, default=False, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved')], default='Open', max_length=10)),
                ('subsystem', models.CharField(choices=[('N/A', 'N/A'), ('Dashboard', 'Dashboard'), ('Orders', 'Orders'), ('Inventory', 'Inventory'), ('Shipments', 'Shipments'), ('Tickets', 'Tickets')], default='N/A', max_length=10)),
                ('opened_by', models.CharField(blank=True, max_length=50, null=True)),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Unshipped', 'Unshipped'), ('Shipped', 'Shipped'), ('Lost', 'Lost'), ('Delayed', 'Delayed'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Unshipped', max_length=10)),
                ('is_express_shipping', models.BooleanField(blank=True, default=False, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('attached_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icetrack.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_order', models.IntegerField(blank=True, default='0', null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icetrack.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icetrack.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, through='icetrack.OrderItem', to='icetrack.Inventory'),
        ),
    ]
