# Generated by Django 3.1.3 on 2020-12-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icetrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_by',
            field=models.CharField(blank=True, default='Administrator', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='package_size',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
