# Generated by Django 3.1.3 on 2020-11-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icetrack', '0002_inventory_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('opened_by', models.CharField(blank=True, max_length=50, null=True)),
                ('date_opened', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
