# Generated by Django 3.1.3 on 2020-12-07 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icetrack', '0002_auto_20201206_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_express_shipping',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped_date',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='attached_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icetrack.order'),
        ),
    ]
