# Generated by Django 3.1.3 on 2020-11-29 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icetrack', '0004_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory',
            field=models.ManyToManyField(blank=True, null=True, to='icetrack.Inventory'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icetrack.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved')], default='Open', max_length=10),
        ),
    ]
