# Generated by Django 3.1.3 on 2020-12-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icetrack', '0005_auto_20201129_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='num_orders',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='package_size',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='state',
            field=models.CharField(choices=[('Actual', 'Actual'), ('Planned', 'Planned'), ('Spoilage', 'Spoilage'), ('Defective', 'Defective')], default='Planned', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='inventory',
            field=models.ManyToManyField(blank=True, to='icetrack.Inventory'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_opened',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
