# Generated by Django 3.1.3 on 2020-12-05 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icetrack', '0006_auto_20201205_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='inventory',
            new_name='inventory_items',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='order',
            new_name='attached_order',
        ),
        migrations.AddField(
            model_name='order',
            name='is_express_shipping',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_express_shipping',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='package_size',
            field=models.DecimalField(blank=True, decimal_places=1, default='0', max_digits=3, null=True),
        ),
    ]
