# Generated by Django 3.1.3 on 2020-12-05 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icetrack', '0007_auto_20201205_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
