# Generated by Django 3.1.3 on 2020-12-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icetrack', '0008_inventory_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Unshipped', 'Unshipped'), ('Shipped', 'Shipped'), ('Lost', 'Lost'), ('Delayed', 'Delayed'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Unshipped', max_length=10),
        ),
    ]
