# Generated by Django 3.1.3 on 2020-12-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icetrack', '0009_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Fulfilled', 'Fulfilled'), ('Canceled', 'Canceled')], default='Placed', max_length=10),
        ),
    ]
