# Generated by Django 3.1.3 on 2020-12-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icetrack', '0010_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subsystem',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Dashboard', 'Dashboard'), ('Orders', 'Orders'), ('Inventory', 'Inventory'), ('Shipments', 'Shipments'), ('Tickets', 'Tickets')], default='N/A', max_length=10),
        ),
    ]
